// USING AxUnit;
// USING ValveLib;
// NAMESPACE MyTest

//     {TestFixture}
//     CLASS MyTestFixture
//         {Test}
//         VAR
//             vinst:valve;
//         END_VAR
        
//         METHOD PUBLIC MyTestMethod
//              VAR_TEMP
//                 result:BOOL;
//              END_VAR
             
//             vinst.Open();            
//             vinst.ValveExcute(result);
//             Assert.Equal(actual := result, expected := TRUE);
//         END_METHOD
//     END_CLASS

// END_NAMESPACE
